static_resources:
    listeners:
        - name: postgres_tls_listener
          address:
              socket_address:
                  address: 0.0.0.0
                  port_value: 15432
          filter_chains:
              - filters:
                    - name: envoy.filters.network.tcp_proxy
                      typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                          stat_prefix: postgres_tls
                          cluster: postgres_upstream
                transport_socket:
                    name: envoy.transport_sockets.tls
                    typed_config:
                        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                        common_tls_context:
                            tls_certificates:
                                - certificate_chain:
                                      filename: "/etc/envoy/certs/tls.crt"
                                  private_key:
                                      filename: "/etc/envoy/certs/tls.key"

    clusters:
        - name: postgres_upstream
          type: STRICT_DNS
          connect_timeout: 1s
          load_assignment:
              cluster_name: postgres_upstream
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: postgres
                                      port_value: 5432
          transport_socket:
              name: envoy.transport_sockets.raw_buffer
              typed_config:
                  "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer

admin:
    address:
        socket_address:
            address: 0.0.0.0
            port_value: 9901
